### ISSUE TITLE
Crashed When I Opened My Rom

### ISSUE THREAD

**Issue by Mariogamer12** [Yoshimaster96/EggFlutter#1]
I Opened My Rom And It Crashed And I Need Help To Fix It! Please And Thank You!
[Super Mario World 2 - Yoshi's Island (USA) (Rev 1).zip](https://github.com/Yoshimaster96/EggFlutter/files/10050922/Super.Mario.World.2.-.Yoshi.s.Island.USA.Rev.1.zip)
Theres The Rom That Does Not Work For Me

**Comment by Yoshimaster96** [comment]
You need to use US version 1.0, you're using version 1.1. However please note that this tool hasn't been maintained in forever, I haven't really been working on this for quite a long time, and I dunno if/when I'll return to it.

 Also it's not a good idea to post ROMs online like that.
